include:
  - board: nice_nano_v2
    shield: DecaDeca_L
  - board: nice_nano_v2
    shield: DecaDeca_R
  - board: nice_nano_v2
    shield: DecaDeca_Split_left
  - board: nice_nano_v2
    shield: DecaDeca_Split_right
  - board: nice_nano_v2
    shield: settings_reset